# Generated by Django 5.0.6 on 2024-08-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_enrollment_course_performance'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='performance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='performance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.DeleteModel(
            name='Performance',
        ),
    ]
