# Generated by Django 5.0.6 on 2024-06-18 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='testimony', to='courses.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rct',
            name='intro',
            field=models.TextField(blank=True, null=True),
        ),
    ]
