# Generated by Django 5.0.6 on 2024-06-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_career'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='international_certification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='payment_guidance',
            field=models.TextField(blank=True, null=True),
        ),
    ]
