# Generated by Django 5.0.6 on 2024-06-18 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_international_certification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='course',
            name='subs',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='image',
        ),
    ]
