# Generated by Django 5.0.6 on 2024-08-14 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_enrollment_overall_performance_perfomance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfomance',
            name='date_recorded',
        ),
    ]
