# Generated by Django 5.0.6 on 2024-06-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_partners_description_partners_logo_partners_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
