# Generated by Django 5.0.6 on 2024-06-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_subscription_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='period_in_weeks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
