# Generated by Django 5.0.6 on 2024-06-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_enrollment_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='course',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='course',
            field=models.ManyToManyField(related_name='enrollments', to='courses.course'),
        ),
    ]
