# Generated by Django 5.0.6 on 2024-06-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_remove_course_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='finishing_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
