# Generated by Django 5.0.6 on 2024-06-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_enrollment_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
