# Generated by Django 5.0.6 on 2024-06-23 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_subject_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='payment_guidance',
        ),
    ]
