# Generated by Django 5.0.6 on 2024-06-24 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_remove_course_payment_guidance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='fee_balance',
        ),
    ]
