# Generated by Django 5.0.6 on 2024-07-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_answer_question_delete_faq_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/partners/buildings'),
        ),
    ]
