# Generated by Django 5.0.6 on 2024-07-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_partners_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='rct',
            name='adress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rct',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rct',
            name='outro',
            field=models.TextField(blank=True, null=True),
        ),
    ]
