# Generated by Django 5.0.6 on 2024-07-03 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_rct_adress_rct_phone_alter_rct_outro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonials',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='testimonials',
            name='course',
        ),
        migrations.RemoveField(
            model_name='testimonials',
            name='occupation',
        ),
        migrations.DeleteModel(
            name='Career',
        ),
    ]
