# Generated by Django 5.0.6 on 2024-07-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_remove_testimonials_image_remove_testimonials_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='cert_image',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='fee',
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrollment_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
